CREATE TABLE `Order` (
  id INT AUTO_INCREMENT PRIMARY KEY,
  token VARCHAR(50) NOT NULL,
  trade_id VARCHAR(50) NOT NULL UNIQUE,
  total_amount INT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT '未付款',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (token) REFERENCES User(token) ON DELETE CASCADE
);