USE shop;

CREATE TABLE User (
  id INT AUTO_INCREMENT PRIMARY KEY,
  token VARCHAR(100) NOT NULL UNIQUE,
  account VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  level INT NOT NULL DEFAULT 1,
  email VARCHAR(255) NOT NULL UNIQUE,
  info JSON NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
